export const defaultCatalog = [
  {id:'cat-termo-asa-yeti',name:'Termo con asa tipo Yeti',category:'Termos',service:'laser',price:320,status:'order',details:'Acero inoxidable, 30 oz / 890 ml. Personalización con grabado.'},
  {id:'cat-termo-asa-generico',name:'Termo con asa genérico',category:'Termos',service:'laser',price:280,status:'order',details:'Acero inoxidable, 30 oz / 890 ml. Personalización con grabado.'},
  {id:'cat-rambler-yeti',name:'Termo Rambler tipo Yeti',category:'Termos',service:'laser',price:250,status:'order',details:'Acero inoxidable, 20 oz / 600 ml.'},
  {id:'cat-rambler-liso',name:'Termo Rambler liso',category:'Termos',service:'laser',price:200,status:'order',details:'Acero inoxidable, 20 oz / 600 ml.'},
  {id:'cat-whiskero',name:'Termo whiskero',category:'Termos',service:'laser',price:180,status:'order',details:'Acero inoxidable, 360 ml.'},
  {id:'cat-coffee-yeti',name:'Coffee mug cup tipo Yeti',category:'Termos',service:'laser',price:290,status:'order',details:'Acero inoxidable, 10 oz.'},
  {id:'cat-coffee-generico',name:'Coffee mug cup genérico',category:'Termos',service:'laser',price:260,status:'order',details:'Acero inoxidable, 10 oz.'},
  {id:'cat-bidon-degradado',name:'Bidón degradado',category:'Termos',service:'cricut',price:100,status:'order',details:'500 ml, personalizado.'},
  {id:'cat-bidon',name:'Bidón personalizado',category:'Termos',service:'cricut',price:90,status:'order',details:'500 ml.'},
  {id:'cat-termo-degradado',name:'Termo degradado con tapa',category:'Termos',service:'cricut',price:110,status:'order',details:'Colores azul o rosa.'},
  {id:'cat-taza-blanca',name:'Taza blanca',category:'Tazas y tarros',service:'cricut',price:50,status:'order',details:'11 oz, personalizada.'},
  {id:'cat-taza-magica',name:'Taza mágica',category:'Tazas y tarros',service:'cricut',price:110,status:'order',details:'11 oz, personalizada.'},
  {id:'cat-taza-colores',name:'Taza de colores',category:'Tazas y tarros',service:'cricut',price:70,status:'order',details:'11 oz.'},
  {id:'cat-taza-cuchara',name:'Taza con cuchara',category:'Tazas y tarros',service:'cricut',price:110,status:'order',details:'11 oz.'},
  {id:'cat-taza-corazon',name:'Taza con asa de corazón',category:'Tazas y tarros',service:'cricut',price:60,status:'order',details:'11 oz.'},
  {id:'cat-taza-glitter',name:'Taza glitter',category:'Tazas y tarros',service:'cricut',price:80,status:'order',details:'11 oz.'},
  {id:'cat-tarro-colores',name:'Tarro de colores',category:'Tazas y tarros',service:'cricut',price:140,status:'order',details:'16 oz.'},
  {id:'cat-placa-premier',name:'Placa de identificación Premier',category:'Placas',service:'laser',price:38,status:'order',details:'Aluminio con grabado de nombre.'},
  {id:'cat-placa-lance',name:'Placa de identificación Lance',category:'Placas',service:'laser',price:38,status:'order',details:'Aluminio con grabado de nombre.'},
  {id:'cat-placa-stevia',name:'Placa de identificación Stevia',category:'Placas',service:'laser',price:38,status:'order',details:'Aluminio con grabado de nombre.'},
  {id:'cat-placa-verdi',name:'Placa de identificación Verdi',category:'Placas',service:'laser',price:38,status:'order',details:'Aluminio con grabado de nombre.'},
  {id:'cat-bitacora-aitana',name:'Libreta bitácora Aitana',category:'Papelería',service:'laser',price:150,status:'order',details:'9 × 14 cm, 80 hojas rayadas, personalizable.'},
  {id:'cat-bitacora-africa',name:'Libreta bitácora África',category:'Papelería',service:'laser',price:150,status:'order',details:'A5, 80 hojas rayadas, personalizable.'},
  {id:'cat-sticker-4',name:'Sticker personalizado 4 cm',category:'Stickers y etiquetas',service:'cricut',price:4,status:'order',details:'Precio unitario; cotizar pedidos mayores de 50 piezas.'},
  {id:'cat-sticker-7',name:'Sticker personalizado 7 cm',category:'Stickers y etiquetas',service:'cricut',price:6,status:'order',details:'Precio unitario; cotizar pedidos mayores de 50 piezas.'},
  {id:'cat-sticker-lam-4',name:'Sticker laminado 4 cm',category:'Stickers y etiquetas',service:'cricut',price:6,status:'order',details:'Precio unitario; laminado en frío.'},
  {id:'cat-sticker-lam-7',name:'Sticker laminado 7 cm',category:'Stickers y etiquetas',service:'cricut',price:8,status:'order',details:'Precio unitario; laminado en frío.'},
  {id:'cat-etiquetas-escolares',name:'Paquete de etiquetas escolares',category:'Stickers y etiquetas',service:'cricut',price:140,status:'order',details:'Incluye etiquetas para colores, libretas, libros y viniles.'},
  {id:'cat-etiquetas-utiles',name:'Paquete de etiquetas para útiles',category:'Stickers y etiquetas',service:'cricut',price:45,status:'order',details:'40 etiquetas para colores o plumas.'},
  {id:'cat-lapices-12',name:'Lápices grabados, docena',category:'Detalles escolares',service:'laser',price:38,status:'order',details:'Grabado de nombre; mínimo 12 piezas.'},
  {id:'cat-lapices-24',name:'Lápices grabados, 24 piezas',category:'Detalles escolares',service:'laser',price:68,status:'order',details:'Grabado de nombre.'},
  {id:'cat-agenda-prof-carta',name:'Agenda de profesiones tamaño carta',category:'Agendas y libretas',service:'cricut',price:380,status:'order',details:'100 a 150 hojas. Precio base.'},
  {id:'cat-agenda-prof-oficio',name:'Agenda de profesiones medio oficio',category:'Agendas y libretas',service:'cricut',price:340,status:'order',details:'100 a 150 hojas. Precio base.'},
  {id:'cat-agenda-prof-media',name:'Agenda de profesiones media carta',category:'Agendas y libretas',service:'cricut',price:320,status:'order',details:'100 a 150 hojas. Precio base.'},
  {id:'cat-libreta-carta',name:'Libreta encuadernada tamaño carta',category:'Agendas y libretas',service:'cricut',price:180,status:'order',details:'100 hojas. Precio desde.'},
  {id:'cat-libreta-oficio',name:'Libreta encuadernada medio oficio',category:'Agendas y libretas',service:'cricut',price:160,status:'order',details:'100 hojas. Precio desde.'},
  {id:'cat-libreta-media',name:'Libreta encuadernada media carta',category:'Agendas y libretas',service:'cricut',price:140,status:'order',details:'100 hojas. Precio desde.'},
  {id:'cat-sello-circular-42',name:'Sello Trodat circular 4.2 cm',category:'Sellos',service:'laser',price:360,status:'order',details:'Diseño incluido.'},
  {id:'cat-sello-circular-45',name:'Sello Trodat circular 4.5 cm',category:'Sellos',service:'laser',price:370,status:'order',details:'Diseño incluido.'},
  {id:'cat-sello-circular-50',name:'Sello Trodat circular 5 cm',category:'Sellos',service:'laser',price:440,status:'order',details:'Diseño incluido.'},
  {id:'cat-sello-fechador-45',name:'Sello circular con fechador 4.5 cm',category:'Sellos',service:'laser',price:550,status:'order',details:'Precio base según modelo.'},
  {id:'cat-sello-rect-64',name:'Sello rectangular 6 × 4 cm',category:'Sellos',service:'laser',price:490,status:'order',details:'Sugerido para rúbrica.'},
  {id:'cat-sello-cuadrado-fecha',name:'Sello cuadrado con fechador 4 × 4 cm',category:'Sellos',service:'laser',price:530,status:'order',details:'Diseño incluido.'},
  {id:'cat-sello-rect-fecha-53',name:'Sello rectangular con fechador 5 × 3 cm',category:'Sellos',service:'laser',price:620,status:'order',details:'Diseño incluido.'},
  {id:'cat-sello-mini',name:'Sello pequeño Mini 2.6 × 0.9 cm',category:'Sellos',service:'laser',price:250,status:'order',details:'Diseño incluido.'},
  {id:'cat-polo-yazbek',name:'Playera tipo polo Yazbek',category:'Textil',service:'cricut',price:250,status:'order',details:'Tallas S, M y L; estampado DTF.'},
  {id:'cat-playera-yazbek',name:'Playera Yazbek 100% algodón',category:'Textil',service:'cricut',price:200,status:'order',details:'Tallas S, M y L; estampado DTF.'},
  {id:'cat-playera-ninos',name:'Playera de niños',category:'Textil',service:'cricut',price:150,status:'order',details:'Tallas CH a 14; estampado DTF.'},
  {id:'cat-sudadera-cerrada',name:'Sudadera cerrada Yazbek',category:'Textil',service:'cricut',price:450,status:'order',details:'Tallas S, M y L; estampado DTF.'},
  {id:'cat-sudadera-cierre',name:'Sudadera con cierre Yazbek',category:'Textil',service:'cricut',price:500,status:'order',details:'Tallas S, M y L; estampado DTF.'},
  {id:'cat-playera-activi',name:'Playera Activi Tee cuello redondo',category:'Textil',service:'cricut',price:200,status:'order',details:'Tallas S, M y L; DTF o sublimación.'},
  {id:'cat-polo-activi',name:'Playera Activi Tee tipo polo',category:'Textil',service:'cricut',price:250,status:'order',details:'Tallas S, M y L; DTF o sublimación.'},
  {id:'cat-bolsa-mini',name:'Bolsa mini personalizada',category:'Bolsas',service:'cricut',price:30,status:'order',details:'20 × 18 cm; estampado DTF.'},
  {id:'cat-bolsa-mini-poliester',name:'Bolsa mini de poliéster',category:'Bolsas',service:'cricut',price:16,status:'order',details:'20 × 19 cm; sublimada.'},
  {id:'cat-bolsa-mini-manta',name:'Bolsa mini de manta',category:'Bolsas',service:'cricut',price:25,status:'order',details:'18 × 19 cm; estampado DTF.'},
  {id:'cat-bolsa-negra',name:'Bolsa grande negra de lona',category:'Bolsas',service:'cricut',price:95,status:'order',details:'35 × 35 cm aprox.; estampado DTF.'},
  {id:'cat-bolsa-manta',name:'Bolsa grande de manta',category:'Bolsas',service:'cricut',price:80,status:'order',details:'35 × 35 cm aprox.; estampado DTF.'},
  {id:'cat-bolsa-colores',name:'Bolsa grande de colores',category:'Bolsas',service:'cricut',price:80,status:'order',details:'Estampado DTF; colores sujetos a disponibilidad.'}
]

export const blankCatalogProduct = {
  name:'',
  category:'Otros',
  service:'laser',
  price:0,
  status:'order',
  details:''
}
