import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {
  Archive, BarChart3, Box, Calculator, Check, ClipboardList, FileText, Flame,
  Menu, MessageCircle, Package, Plus, Printer, RotateCcw, Save, Search,
  Scissors, Settings, Trash2, UserRound, Users, X
} from 'lucide-react'
import './styles.css'
import './service.css'
import {blankCatalogProduct, defaultCatalog} from './catalogData'

const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v)||0)
const num=v=>Number(v)||0
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`
const today=()=>new Date().toISOString().slice(0,10)
const defaults={businessName:'A&E Studio Laser',phone:'',printer:'Bambu Lab A1',electricityPrice:1.2,printerWatts:90,wearPerHour:5,laserRate:80,cricutRate:40,defaultProfit:50,roundTo:5,quoteValidity:15,
  materials:[{id:'pla',name:'PLA',priceKg:298},{id:'petg',name:'PETG',priceKg:340}],
  laserMaterials:[{id:'mdf3',name:'MDF 3 mm',pricingMode:'sheet',sheetWidth:120,sheetHeight:240,sheetCost:160,waste:0},{id:'acrylic3',name:'Acrílico 3 mm',pricingMode:'sheet',sheetWidth:60,sheetHeight:40,sheetCost:240,waste:10},{id:'tumbler',name:'Termo para grabado',pricingMode:'unit',sheetWidth:0,sheetHeight:0,sheetCost:0,waste:0},{id:'steelplate',name:'Placa inoxidable',pricingMode:'unit',sheetWidth:0,sheetHeight:0,sheetCost:0,waste:0}],
  cricutMaterials:[{id:'vinyl',name:'Vinil adhesivo',pricingMode:'meter',sheetWidth:60,sheetHeight:100,sheetCost:65,waste:5},{id:'sticker',name:'Papel sticker A4',pricingMode:'sheet',sheetWidth:21,sheetHeight:29.7,sheetCost:12,waste:8},{id:'cardstock',name:'Cartulina 12 × 12',pricingMode:'sheet',sheetWidth:30.5,sheetHeight:30.5,sheetCost:15,waste:8}]}
const freshQuote=s=>({client:'',project:'',catalogProduct:'',material:s.materials[0]?.id||'pla',quantity:1,weight:50,hours:4,minutes:0,extras:0,labor:0,profit:num(s.defaultProfit)||50})
const freshStock={type:'product',name:'',category:'laser',supplier:'',purchaseQty:1,purchaseTotal:0,stock:1,minStock:0,salePrice:0,purchaseDate:today()}
const freshClient={name:'',phone:'',email:'',notes:''}
const unitCost=i=>num(i.purchaseTotal)/Math.max(1,num(i.purchaseQty))
const categoryName=id=>({laser:'Láser','3d':'Impresión 3D',cricut:'Cricut'}[id]||'Sin categoría')

function useLocal(key,initial,legacy){
  const [value,setValue]=useState(()=>{try{const v=localStorage.getItem(key);if(v)return JSON.parse(v);if(legacy){const old=localStorage.getItem(legacy);if(old)return JSON.parse(old)}}catch{}return typeof initial==='function'?initial():initial})
  useEffect(()=>localStorage.setItem(key,JSON.stringify(value)),[key,value])
  return [value,setValue]
}

function App(){
  const [page,setPage]=useState('dashboard'),[open,setOpen]=useState(false)
  const [settings,setSettings]=useLocal('ae_settings_v10',()=>{try{const old=JSON.parse(localStorage.getItem('ae_settings_v7')||localStorage.getItem('ae_settings_v5')||localStorage.getItem('ae_stage1_settings')||'{}'),laser=old.laserMaterials||defaults.laserMaterials,extra=defaults.laserMaterials.filter(d=>!laser.some(m=>m.id===d.id));return{...defaults,...old,laserMaterials:[...laser,...extra],cricutMaterials:old.cricutMaterials||defaults.cricutMaterials}}catch{return defaults}})
  const [quotes,setQuotes]=useLocal('ae_quotes_v5',[],'ae_stage1_history')
  const [orders,setOrders]=useLocal('ae_orders_v5',[])
  const [inventory,setInventory]=useLocal('ae_inventory_v5',[])
  const [catalog,setCatalog]=useLocal('ae_catalog_v1',defaultCatalog)
  const [clients,setClients]=useLocal('ae_clients_v5',[])
  const [models,setModels]=useLocal('ae_models_v5',[])
  useEffect(()=>{'serviceWorker'in navigator&&navigator.serviceWorker.register('/sw.js').catch(()=>{})},[])
  const nav=[['dashboard','Resumen',BarChart3],['quote','Impresión 3D',Calculator],['laser','Láser',Flame],['cricut','Cricut',Scissors],['catalog','Catálogo',Archive],['orders','Pedidos',ClipboardList],['inventory','Inventario',Package],['clients','Clientes',Users],['quotes','Cotizaciones',FileText],['models','Modelos 3D',Box],['settings','Configuración',Settings]]
  const go=id=>{setPage(id);setOpen(false)}
  return <div className="appShell">
    <aside className={`sidebar ${open?'open':''}`}><div className="brand"><img src="/logo-ae.png" alt="A&E Studio Laser"/><div><strong>A&E Studio Laser</strong><span>Gestión del taller</span></div></div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={19}/>{label}</button>)}</nav><small>Datos guardados en este dispositivo</small></aside>
    {open&&<button className="scrim" onClick={()=>setOpen(false)} aria-label="Cerrar menú"/>}
    <main className="main"><header className="topbar"><button className="menuButton" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><h1>{nav.find(n=>n[0]===page)?.[1]}</h1><p>A&E Studio Laser</p></div></header>
      <div className="content">
        {page==='dashboard'&&<Dashboard orders={orders} inventory={inventory} quotes={quotes} go={go}/>}
        {page==='quote'&&<Quote settings={settings} inventory={inventory} catalog={catalog} quotes={quotes} setQuotes={setQuotes} orders={orders} setOrders={setOrders} clients={clients} setClients={setClients} models={models} setModels={setModels}/>}
        {page==='laser'&&<ServiceQuote service="laser" inventory={inventory} catalog={catalog} settings={settings} quotes={quotes} setQuotes={setQuotes} orders={orders} setOrders={setOrders} clients={clients} setClients={setClients}/>}
        {page==='cricut'&&<ServiceQuote service="cricut" inventory={inventory} catalog={catalog} settings={settings} quotes={quotes} setQuotes={setQuotes} orders={orders} setOrders={setOrders} clients={clients} setClients={setClients}/>}
        {page==='catalog'&&<Catalog products={catalog} setProducts={setCatalog}/>}
        {page==='orders'&&<Orders orders={orders} setOrders={setOrders}/>}
        {page==='inventory'&&<Inventory items={inventory} setItems={setInventory}/>}
        {page==='clients'&&<Clients clients={clients} setClients={setClients}/>}
        {page==='quotes'&&<Quotes quotes={quotes} setQuotes={setQuotes}/>}
        {page==='models'&&<Models models={models} setModels={setModels} settings={settings}/>}
        {page==='settings'&&<SettingsPage settings={settings} setSettings={setSettings}/>}
      </div></main>
  </div>
}

function Dashboard({orders,inventory,quotes,go}){
  const delivered=orders.filter(o=>o.status==='delivered'),sales=delivered.reduce((s,o)=>s+num(o.total),0),cost=delivered.reduce((s,o)=>s+num(o.productionCost),0)
  const pending=orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length,low=inventory.filter(i=>num(i.stock)<=num(i.minStock)),investment=inventory.reduce((s,i)=>s+unitCost(i)*num(i.stock),0)
  return <><section className="hero"><div><span>Panel del negocio</span><h2>Todo tu taller en un solo lugar</h2><p>Cotiza, controla pedidos y conoce el valor de tu inventario.</p></div><button className="primary" onClick={()=>go('quote')}><Plus size={18}/>Nueva cotización</button></section>
    <div className="stats"><Stat label="Ventas entregadas" value={money(sales)} tone="blue"/><Stat label="Utilidad estimada" value={money(sales-cost)} tone="green"/><Stat label="Pedidos activos" value={pending} tone="orange"/><Stat label="Inventario invertido" value={money(investment)} tone="purple"/></div>
    <div className="twoColumns"><Card title="Pedidos recientes" subtitle={`${orders.length} registrados`}>{orders.length?orders.slice(0,5).map(o=><div className="listRow" key={o.id}><div><b>{o.project||'Pedido'}</b><span>{o.client||'Sin cliente'}</span></div><div className="right"><Status value={o.status}/><b>{money(o.total)}</b></div></div>):<Empty text="Aún no hay pedidos."/>}</Card>
      <Card title="Alertas de inventario" subtitle={`${low.length} con existencia baja`}>{low.length?low.slice(0,6).map(i=><div className="listRow" key={i.id}><div><b>{i.name}</b><span>{i.category||'Sin categoría'}</span></div><span className="stockAlert">{num(i.stock)} disponibles</span></div>):<Empty text="Sin alertas de existencias."/>}</Card></div>
    <Card title="Actividad" subtitle="Información capturada"><div className="activity"><button onClick={()=>go('quotes')}><FileText/><b>{quotes.length}</b><span>Cotizaciones</span></button><button onClick={()=>go('orders')}><ClipboardList/><b>{orders.length}</b><span>Pedidos</span></button><button onClick={()=>go('inventory')}><Package/><b>{inventory.length}</b><span>Artículos</span></button></div></Card>
  </>
}

function Quote({settings,inventory,catalog,quotes,setQuotes,orders,setOrders,clients,setClients,models,setModels}){
  const [form,setForm]=useState(()=>freshQuote(settings)),[saved,setSaved]=useState(false)
  const inventoryMaterials=(inventory||[]).filter(i=>i.category==='3d'&&num(i.stock)>0).map(i=>({id:`stock-${i.id}`,name:`${i.name} (Inventario)`,priceKg:unitCost(i),inventoryId:i.id})),materialCatalog=[...(settings.materials||[]),...inventoryMaterials],catalogProducts=(catalog||[]).filter(p=>(p.service==='3d'||p.service==='all')&&p.status!=='hidden')
  const update=(k,v)=>{setSaved(false);setForm({...form,[k]:v})},material=materialCatalog.find(m=>m.id===form.material)||materialCatalog[0]||{name:'Material',priceKg:0},catalogItem=catalogProducts.find(p=>p.id===form.catalogProduct)
  const calc=useMemo(()=>{const qty=Math.max(1,num(form.quantity)),h=num(form.hours)+num(form.minutes)/60,materialCost=num(form.weight)/1000*num(material.priceKg),electricity=h*num(settings.printerWatts)/1000*num(settings.electricityPrice),wear=h*num(settings.wearPerHour),productionCost=materialCost+electricity+wear+num(form.labor)+num(form.extras),raw=productionCost*(1+num(form.profit)/100),catalogBase=num(catalogItem?.price)*qty,step=Math.max(1,num(settings.roundTo)),total=Math.ceil(Math.max(raw,catalogBase)/step)*step;return{printHours:h,materialCost,electricity,wear,productionCost,catalogBase,profitAmount:total-productionCost,total,unit:total/qty}},[form,material,catalogItem,settings])
  const snapshot=()=>({id:uid(),folio:`COT-${Date.now().toString().slice(-7)}`,date:new Date().toISOString(),...form,materialName:material.name,catalogName:catalogItem?.name||'',...calc})
  const ensureClient=()=>{const name=form.client.trim();if(name&&!clients.some(c=>c.name.toLowerCase()===name.toLowerCase()))setClients([{id:uid(),name,phone:'',email:'',notes:''},...clients])}
  const save=()=>{const q=snapshot();setQuotes([q,...quotes]);ensureClient();setSaved(true);return q}
  const order=()=>{const q=save();setOrders([{...q,id:uid(),quoteId:q.id,status:'pending',createdAt:new Date().toISOString(),dueDate:''},...orders]);alert('Cotización guardada y pedido creado.')}
  const message=()=>encodeURIComponent(`*${settings.businessName||'A&E Studio Laser'}*\nCotización\nCliente: ${form.client||'—'}\nProyecto: ${form.project||catalogItem?.name||'—'}\n${catalogItem?`Producto: ${catalogItem.name}\n`:''}Material: ${material.name}\nCantidad: ${form.quantity}\nPrecio por pieza: ${money(calc.unit)}\n*Total: ${money(calc.total)}*\nVigencia: ${settings.quoteValidity||15} días`)
  const saveModel=()=>{if(!form.project.trim())return alert('Escribe el proyecto.');setModels([{id:uid(),name:form.project.trim(),material:form.material,weight:form.weight,hours:form.hours,minutes:form.minutes},...models]);alert('Modelo guardado.')}
  const loadModel=id=>{const m=models.find(x=>x.id===id);if(m)setForm({...form,project:m.name,material:m.material,weight:m.weight,hours:m.hours,minutes:m.minutes})}
  return <div className="quoteLayout"><Card title="Nueva cotización" subtitle="Captura solo los datos necesarios.">
    {models.length>0&&<Field label="Cargar modelo guardado" full><select defaultValue="" onChange={e=>{loadModel(e.target.value);e.target.value=''}}><option value="">Seleccionar modelo…</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>}
    {catalogProducts.length>0&&<Field label="Producto del catálogo (opcional)" full><select value={form.catalogProduct} onChange={e=>{const item=catalogProducts.find(p=>p.id===e.target.value);setForm({...form,catalogProduct:e.target.value,project:form.project||item?.name||''});setSaved(false)}}><option value="">Cotización desde cero</option>{catalogProducts.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></Field>}
    <div className="formGrid"><Field label="Cliente"><input value={form.client} onChange={e=>update('client',e.target.value)} placeholder="Nombre del cliente"/></Field><Field label="Proyecto"><input value={form.project} onChange={e=>update('project',e.target.value)} placeholder="Ej. Llavero personalizado"/></Field>
      <Field label="Material"><select value={form.material} onChange={e=>update('material',e.target.value)}><optgroup label="Materiales configurados">{(settings.materials||[]).map(m=><option key={m.id} value={m.id}>{m.name} — {money(m.priceKg)}/kg</option>)}</optgroup>{inventoryMaterials.length>0&&<optgroup label="Inventario de Impresión 3D">{inventoryMaterials.map(m=><option key={m.id} value={m.id}>{m.name} — {money(m.priceKg)}/kg</option>)}</optgroup>}</select></Field><Field label="Cantidad"><input type="number" min="1" value={form.quantity} onChange={e=>update('quantity',e.target.value)}/></Field>
      <Field label="Peso total (g)"><input type="number" min="0" value={form.weight} onChange={e=>update('weight',e.target.value)}/></Field><div className="splitFields"><Field label="Horas"><input type="number" min="0" value={form.hours} onChange={e=>update('hours',e.target.value)}/></Field><Field label="Minutos"><input type="number" min="0" max="59" value={form.minutes} onChange={e=>update('minutes',e.target.value)}/></Field></div>
      <Field label="Extras ($)"><input type="number" min="0" value={form.extras} onChange={e=>update('extras',e.target.value)}/></Field><Field label="Mano de obra ($)"><input type="number" min="0" value={form.labor} onChange={e=>update('labor',e.target.value)}/></Field><Field label={`Ganancia: ${form.profit}%`} full><input type="range" min="0" max="150" value={form.profit} onChange={e=>update('profit',e.target.value)}/></Field></div>
    {saved&&<div className="success"><Check size={17}/>Cotización guardada</div>}<div className="actions"><button className="primary" onClick={save}><Save size={18}/>Guardar</button><button onClick={order}><ClipboardList size={18}/>Crear pedido</button><button onClick={()=>window.location.href=`https://wa.me/?text=${message()}`}><MessageCircle size={18}/>WhatsApp</button><button onClick={()=>window.print()}><Printer size={18}/>PDF / Imprimir</button><button onClick={saveModel}><Archive size={18}/>Guardar modelo</button><button onClick={()=>{setForm(freshQuote(settings));setSaved(false)}}><RotateCcw size={18}/>Nueva</button></div>
  </Card><aside className="resultCard printArea"><img src="/logo-ae.png" className="printLogo" alt="A&E Studio Laser"/><span>Total sugerido</span><strong>{money(calc.total)}</strong><div className="unitPrice"><span>Precio por pieza</span><b>{money(calc.unit)}</b></div><h3>Desglose</h3>{calc.catalogBase>0&&<Line label="Precio base de catálogo" value={calc.catalogBase}/>}<Line label="Material" value={calc.materialCost}/><Line label="Electricidad" value={calc.electricity}/><Line label="Desgaste" value={calc.wear}/><Line label="Mano de obra" value={form.labor}/><Line label="Extras" value={form.extras}/><Line label="Costos conocidos" value={calc.productionCost} bold/><Line label={catalogItem?'Diferencia sobre costos conocidos':'Ganancia'} value={calc.profitAmount}/><small>{catalogItem?'Se respeta como mínimo el precio vigente del catálogo. ':''}Vigencia: {settings.quoteValidity||15} días</small></aside></div>
}

function ServiceQuote({service,inventory,catalog:productCatalog,settings,quotes,setQuotes,orders,setOrders,clients,setClients}){
  const isLaser=service==='laser',baseCatalog=(isLaser?settings.laserMaterials:settings.cricutMaterials)|| (isLaser?defaults.laserMaterials:defaults.cricutMaterials),inventoryCatalog=(inventory||[]).filter(i=>i.category===service&&num(i.stock)>0).map(i=>({id:`stock-${i.id}`,name:`${i.name} (Inventario: ${num(i.stock)})`,pricingMode:'unit',sheetWidth:0,sheetHeight:0,sheetCost:unitCost(i),waste:0,inventoryId:i.id})),catalog=[...baseCatalog,...inventoryCatalog],catalogProducts=(productCatalog||[]).filter(p=>(p.service===service||p.service==='all')&&p.status!=='hidden')
  const initial={client:'',project:'',catalogProduct:'',jobType:isLaser?'cut':'vinyl',materialSource:'studio',material:catalog[0]?.id||'',quantity:1,width:isLaser?30:10,height:isLaser?30:10,hours:0,minutes:isLaser?20:10,labor:0,design:0,assembly:0,extras:0,profit:num(settings.defaultProfit)||50,manualMaterial:'',fullSheet:false,advanced:false}
  const [form,setForm]=useState(initial),[saved,setSaved]=useState(false)
  const update=(k,v)=>{setSaved(false);setForm({...form,[k]:v})},material=catalog.find(m=>m.id===form.material)||catalog[0]||{name:'Material',sheetWidth:1,sheetHeight:1,sheetCost:0,waste:10},catalogItem=catalogProducts.find(p=>p.id===form.catalogProduct)
  const calc=useMemo(()=>{
    const w=Math.max(.1,num(form.width)),h=Math.max(.1,num(form.height)),qty=Math.max(1,num(form.quantity)),sw=Math.max(.1,num(material.sheetWidth)),sh=Math.max(.1,num(material.sheetHeight)),waste=Math.max(0,num(material.waste))/100,isMeter=material.pricingMode==='meter',isUnit=material.pricingMode==='unit'
    const across=Math.max(1,Math.floor(sw/w)),down=Math.max(1,Math.floor(sh/h)),grid=across*down,areaCapacity=Math.max(1,Math.floor(sw*sh/(w*h*(1+waste)))),perSheet=Math.max(1,Math.min(grid,areaCapacity)),sheets=Math.ceil(qty/perSheet),rows=Math.ceil(qty/across),usedLength=rows*h*(1+waste)
    const proportionalUnit=num(material.sheetCost)/perSheet,includeMaterial=form.materialSource==='studio',automaticMaterial=isUnit?num(material.sheetCost)*qty:isMeter?(usedLength/100)*num(material.sheetCost):(form.fullSheet?sheets*num(material.sheetCost):proportionalUnit*qty),materialCost=includeMaterial?(form.manualMaterial===''?automaticMaterial:num(form.manualMaterial)):0,materialUnit=materialCost/qty,machineHours=num(form.hours)+num(form.minutes)/60,rate=isLaser?num(settings.laserRate||defaults.laserRate):num(settings.cricutRate||defaults.cricutRate),machineCost=machineHours*rate,productionCost=materialCost+machineCost+num(form.labor)+num(form.design)+num(form.assembly)+num(form.extras),raw=productionCost*(1+num(form.profit)/100),catalogBase=num(catalogItem?.price)*qty,step=Math.max(1,num(settings.roundTo)),total=Math.ceil(Math.max(raw,catalogBase)/step)*step
    return{perSheet,sheets,materialUnit,materialCost,machineHours,machineCost,productionCost,catalogBase,total,unit:total/qty,profitAmount:total-productionCost,isMeter,isUnit,usedLength,across}
  },[form,material,catalogItem,isLaser,settings])
  const typeName=isLaser?({cut:'Corte',engrave:'Grabado',both:'Corte y grabado'}[form.jobType]):({vinyl:'Vinil',stickers:'Stickers',paper:'Papel/cartulina',printcut:'Impresión y corte'}[form.jobType])
  const snapshot=()=>({id:uid(),folio:`COT-${Date.now().toString().slice(-7)}`,date:new Date().toISOString(),service:isLaser?'Láser':'Cricut',...form,materialName:material.name,catalogName:catalogItem?.name||'',typeName,...calc})
  const client=()=>{const n=form.client.trim();if(n&&!clients.some(c=>c.name.toLowerCase()===n.toLowerCase()))setClients([{id:uid(),name:n,phone:'',email:'',notes:''},...clients])}
  const save=()=>{const q=snapshot();setQuotes([q,...quotes]);client();setSaved(true);return q}
  const order=()=>{const q=save();setOrders([{...q,id:uid(),quoteId:q.id,status:'pending',createdAt:new Date().toISOString(),dueDate:''},...orders]);alert('Cotización guardada y pedido creado.')}
  const message=()=>encodeURIComponent(`*${settings.businessName||'A&E Studio Laser'}*\nCotización de ${isLaser?'láser':'Cricut'}\nCliente: ${form.client||'—'}\nProyecto: ${form.project||catalogItem?.name||'—'}\n${catalogItem?`Producto: ${catalogItem.name}\n`:''}Trabajo: ${typeName}\nMedidas: ${form.width} × ${form.height} cm\nCantidad: ${form.quantity}\nPrecio por pieza: ${money(calc.unit)}\n*Total: ${money(calc.total)}*\nVigencia: ${settings.quoteValidity||15} días`)
  return <div className="quoteLayout"><Card title={`Cotizador ${isLaser?'láser':'Cricut'}`} subtitle="Medidas y tiempo de máquina para un resultado realista.">
    <Field label="Producto del catálogo (opcional)" full><select value={form.catalogProduct} onChange={e=>{const item=catalogProducts.find(p=>p.id===e.target.value);setForm({...form,catalogProduct:e.target.value,project:form.project||item?.name||'',materialSource:item?'catalog':'studio'});setSaved(false)}}><option value="">Cotización desde cero</option>{catalogProducts.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></Field>
    <div className="formGrid">
    <Field label="Cliente"><input value={form.client} onChange={e=>update('client',e.target.value)} placeholder="Nombre del cliente"/></Field><Field label="Proyecto"><input value={form.project} onChange={e=>update('project',e.target.value)} placeholder={isLaser?'Ej. Caja para regalo':'Ej. Stickers personalizados'}/></Field>
    <Field label="Tipo de trabajo"><select value={form.jobType} onChange={e=>{const jobType=e.target.value;setForm({...form,jobType,materialSource:isLaser&&jobType==='engrave'?'client':'studio'});setSaved(false)}}>{isLaser?<><option value="cut">Corte</option><option value="engrave">Grabado</option><option value="both">Corte y grabado</option></>:<><option value="vinyl">Vinil</option><option value="stickers">Stickers</option><option value="paper">Papel / cartulina</option><option value="printcut">Impresión y corte</option></>}</select></Field>
    <Field label="Origen del material o pieza"><select value={form.materialSource} onChange={e=>update('materialSource',e.target.value)}><option value="studio">Lo proporciona A&E</option><option value="client">Lo proporciona el cliente</option>{catalogItem&&<option value="catalog">Incluido en el precio del catálogo</option>}</select></Field>
    <Field label="Material"><select disabled={form.materialSource!=='studio'} value={form.material} onChange={e=>update('material',e.target.value)}><optgroup label="Materiales configurados">{baseCatalog.map(m=><option key={m.id} value={m.id}>{m.name} — {money(m.sheetCost)}</option>)}</optgroup>{inventoryCatalog.length>0&&<optgroup label={`Inventario de ${isLaser?'Láser':'Cricut'}`}>{inventoryCatalog.map(m=><option key={m.id} value={m.id}>{m.name} — {money(m.sheetCost)} c/u</option>)}</optgroup>}</select></Field>
    <Field label="Cantidad"><input type="number" min="1" value={form.quantity} onChange={e=>update('quantity',e.target.value)}/></Field><div className="splitFields"><Field label="Ancho de pieza (cm)"><input type="number" min=".1" step=".1" value={form.width} onChange={e=>update('width',e.target.value)}/></Field><Field label="Alto de pieza (cm)"><input type="number" min=".1" step=".1" value={form.height} onChange={e=>update('height',e.target.value)}/></Field></div>
    <div className="splitFields"><Field label="Horas de máquina"><input type="number" min="0" value={form.hours} onChange={e=>update('hours',e.target.value)}/></Field><Field label="Minutos"><input type="number" min="0" max="59" value={form.minutes} onChange={e=>update('minutes',e.target.value)}/></Field></div><Field label="Mano de obra ($)"><input type="number" min="0" value={form.labor} onChange={e=>update('labor',e.target.value)}/></Field>
    <Field label={`Ganancia: ${form.profit}%`} full><input type="range" min="0" max="150" value={form.profit} onChange={e=>update('profit',e.target.value)}/></Field></div>
    <button className="detailsToggle" onClick={()=>update('advanced',!form.advanced)}>{form.advanced?'Ocultar detalles':'Más detalles opcionales'}</button>
    {form.advanced&&<div className="formGrid advancedBox"><Field label="Diseño / preparación ($)"><input type="number" min="0" value={form.design} onChange={e=>update('design',e.target.value)}/></Field><Field label="Armado / acabado ($)"><input type="number" min="0" value={form.assembly} onChange={e=>update('assembly',e.target.value)}/></Field><Field label="Extras ($)"><input type="number" min="0" value={form.extras} onChange={e=>update('extras',e.target.value)}/></Field><Field label="Costo de material manual ($)"><input type="number" min="0" value={form.manualMaterial} placeholder={money(calc.materialCost)} onChange={e=>update('manualMaterial',e.target.value)}/></Field>{!calc.isMeter&&!calc.isUnit&&<label className="checkField"><input type="checkbox" checked={form.fullSheet} onChange={e=>update('fullSheet',e.target.checked)}/><span>Cobrar placa u hoja completa</span></label>}</div>}
    {catalogItem&&<div className="usageNote catalogQuoteNote"><b>{catalogItem.name}: {money(catalogItem.price)} por pieza</b><span>Este precio de catálogo se respeta como mínimo. No descuenta existencias porque el producto está marcado como sobre pedido.</span></div>}
    <div className="usageNote">{form.materialSource==='catalog'?<><b>Producto incluido en el precio del catálogo</b><span>No se suma nuevamente como material. Si necesitas recalcularlo con un costo de compra actual, cambia el origen a “Lo proporciona A&E”.</span></>:form.materialSource==='client'?<><b>Material proporcionado por el cliente</b><span>El costo del material es $0. Solo se cobran máquina, diseño, mano de obra, acabado y extras.</span></>:calc.isUnit?<><b>{form.quantity} producto(s) a {money(material.sheetCost)} cada uno</b><span>Costo del producto base: {money(calc.materialCost)}. Configura el costo de compra por pieza en Configuración.</span></>:calc.isMeter?<><b>{calc.across} pieza(s) a lo ancho · {calc.usedLength.toFixed(1)} cm lineales utilizados</b><span>Costo del vinil utilizado: {money(calc.materialCost)} · rollo de {material.sheetWidth} cm de ancho a {money(material.sheetCost)} por metro · merma {material.waste||0}%.</span></>:<><b>{calc.perSheet} pieza(s) por placa/hoja · {calc.sheets} necesarias</b><span>Costo proporcional por pieza: {money(calc.materialUnit)} · formato de {material.sheetWidth} × {material.sheetHeight} cm a {money(material.sheetCost)} · merma {material.waste||0}%.</span></>}</div>
    {saved&&<div className="success"><Check size={17}/>Cotización guardada</div>}<div className="actions"><button className="primary" onClick={save}><Save size={18}/>Guardar</button><button onClick={order}><ClipboardList size={18}/>Crear pedido</button><button onClick={()=>window.location.href=`https://wa.me/?text=${message()}`}><MessageCircle size={18}/>WhatsApp</button><button onClick={()=>window.print()}><Printer size={18}/>PDF / Imprimir</button><button onClick={()=>{setForm(initial);setSaved(false)}}><RotateCcw size={18}/>Nueva</button></div>
  </Card><aside className="resultCard printArea"><img src="/logo-ae.png" className="printLogo" alt="A&E Studio Laser"/><span>Total sugerido</span><strong>{money(calc.total)}</strong><div className="unitPrice"><span>Precio por pieza</span><b>{money(calc.unit)}</b></div><h3>Desglose</h3>{calc.catalogBase>0&&<Line label="Precio base de catálogo" value={calc.catalogBase}/>}<Line label="Material" value={calc.materialCost}/><Line label="Tiempo de máquina" value={calc.machineCost}/><Line label="Diseño" value={form.design}/><Line label="Mano de obra" value={form.labor}/><Line label="Armado / acabado" value={form.assembly}/><Line label="Extras" value={form.extras}/><Line label="Costos conocidos" value={calc.productionCost} bold/><Line label={catalogItem?'Diferencia sobre costos conocidos':'Ganancia'} value={calc.profitAmount}/><small>{catalogItem?'Precio de catálogo usado como mínimo · ':''}{typeName} · {form.width} × {form.height} cm</small></aside></div>
}

const catalogStatus={order:'Sobre pedido',available:'Disponible',hidden:'Oculto'}
function Catalog({products,setProducts}){
  const [form,setForm]=useState(blankCatalogProduct),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[service,setService]=useState('all'),[category,setCategory]=useState('all')
  const categories=[...new Set(products.map(p=>p.category).filter(Boolean))].sort(),shown=products.filter(p=>(service==='all'||p.service===service||p.service==='all')&&(category==='all'||p.category===category)&&`${p.name} ${p.category} ${p.details}`.toLowerCase().includes(search.toLowerCase()))
  const save=()=>{if(!form.name.trim())return alert('Escribe el nombre del producto.');const item={...form,id:editing||uid(),price:num(form.price)};setProducts(editing?products.map(p=>p.id===editing?item:p):[item,...products]);setForm(blankCatalogProduct);setEditing(null)}
  const edit=p=>{setForm({...blankCatalogProduct,...p});setEditing(p.id);scrollTo({top:0,behavior:'smooth'})}
  return <><section className="catalogHero"><div><span>Importado desde tu catálogo de Canva</span><h2>{products.length} productos listos para cotizar</h2><p>Son productos sobre pedido: no se cuentan como inventario físico.</p></div><div><b>Precios de venta</b><small>Revísalos cuando cambie tu catálogo.</small></div></section>
    <Card title={editing?'Editar producto':'Agregar producto al catálogo'} subtitle="Guarda productos que puedes ofrecer aunque no los tengas físicamente."><div className="formGrid">
      <Field label="Producto"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej. Termo de 20 oz"/></Field>
      <Field label="Categoría"><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Ej. Termos"/></Field>
      <Field label="Cotizador"><select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option value="laser">Láser</option><option value="cricut">Cricut</option><option value="3d">Impresión 3D</option><option value="all">Todos</option></select></Field>
      <Field label="Precio de venta ($)"><input type="number" min="0" step=".01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></Field>
      <Field label="Disponibilidad"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="order">Sobre pedido</option><option value="available">Disponible</option><option value="hidden">Oculto</option></select></Field>
      <Field label="Detalles"><input value={form.details} onChange={e=>setForm({...form,details:e.target.value})} placeholder="Medida, capacidad, material o variante"/></Field>
    </div><div className="actions"><button className="primary" onClick={save}><Save size={18}/>{editing?'Guardar cambios':'Agregar producto'}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(blankCatalogProduct)}}>Cancelar</button>}<button onClick={()=>confirm('¿Restaurar los productos importados desde Canva?')&&setProducts(defaultCatalog)}><RotateCcw size={18}/>Restaurar catálogo</button></div></Card>
    <Card title="Productos" subtitle={`${shown.length} visibles con estos filtros`}><SearchBox value={search} setValue={setSearch} placeholder="Buscar producto, categoría o detalle…"/><div className="catalogFilters"><select value={service} onChange={e=>setService(e.target.value)}><option value="all">Todos los cotizadores</option><option value="laser">Láser</option><option value="cricut">Cricut</option><option value="3d">Impresión 3D</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas las categorías</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></div>
      {shown.length?<div className="catalogGrid">{shown.map(p=><article className="catalogCard" key={p.id}><div className="catalogTop"><span>{p.category}</span><span className={`catalogBadge ${p.status}`}>{catalogStatus[p.status]||'Sobre pedido'}</span></div><h3>{p.name}</h3><p>{p.details||'Producto personalizable.'}</p><div className="catalogBottom"><strong>{money(p.price)}</strong><small>{p.service==='laser'?'Láser':p.service==='cricut'?'Cricut':p.service==='3d'?'Impresión 3D':'Todos'}</small></div><div className="rowActions"><button onClick={()=>edit(p)}>Editar</button><button className="iconButton danger" aria-label={`Eliminar ${p.name}`} onClick={()=>confirm(`¿Eliminar ${p.name}?`)&&setProducts(products.filter(x=>x.id!==p.id))}><Trash2 size={16}/></button></div></article>)}</div>:<Empty text="No hay productos con estos filtros."/>}</Card></>
}

const labels={pending:'Pendiente',process:'En proceso',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado'}
function Status({value}){return <span className={`status ${value}`}>{labels[value]||value}</span>}
function Orders({orders,setOrders}){
  const [filter,setFilter]=useState('all'),shown=filter==='all'?orders:orders.filter(o=>o.status===filter),update=(id,p)=>setOrders(orders.map(o=>o.id===id?{...o,...p}:o))
  return <Card title="Pedidos" subtitle="Seguimiento desde la cotización hasta la entrega."><div className="filters">{['all','pending','process','ready','delivered'].map(id=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{id==='all'?'Todos':labels[id]}</button>)}</div>
    {shown.length?<div className="cardsList">{shown.map(o=><article className="orderCard" key={o.id}><div><Status value={o.status}/><h3>{o.project||'Pedido'}</h3><p>{o.client||'Sin cliente'} · {o.quantity} pieza(s)</p></div><b className="orderTotal">{money(o.total)}</b><Field label="Estado"><select value={o.status} onChange={e=>update(o.id,{status:e.target.value})}>{Object.entries(labels).map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></Field><Field label="Entrega"><input type="date" value={o.dueDate||''} onChange={e=>update(o.id,{dueDate:e.target.value})}/></Field><button className="iconButton danger" onClick={()=>confirm('¿Eliminar este pedido?')&&setOrders(orders.filter(x=>x.id!==o.id))}><Trash2 size={17}/></button></article>)}</div>:<Empty text="No hay pedidos en este estado."/>}</Card>
}

function Inventory({items,setItems}){
  const [form,setForm]=useState(freshStock),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),shown=items.filter(i=>`${i.name} ${i.category} ${i.supplier}`.toLowerCase().includes(search.toLowerCase()))
  const save=()=>{if(!form.name.trim())return alert('Escribe el nombre.');const item={...form,id:editing||uid(),updatedAt:new Date().toISOString()};setItems(editing?items.map(i=>i.id===editing?item:i):[item,...items]);setForm(freshStock);setEditing(null)}
  const investment=items.reduce((s,i)=>s+unitCost(i)*num(i.stock),0),potential=items.reduce((s,i)=>s+num(i.salePrice)*num(i.stock),0)
  return <><div className="stats compact"><Stat label="Artículos" value={items.length} tone="blue"/><Stat label="Dinero invertido" value={money(investment)} tone="purple"/><Stat label="Venta potencial" value={money(potential)} tone="green"/><Stat label="Stock bajo" value={items.filter(i=>num(i.stock)<=num(i.minStock)).length} tone="orange"/></div>
    <Card title={editing?'Editar artículo':'Agregar al inventario'} subtitle="Materia prima o productos como vasos y termos."><div className="formGrid"><Field label="Tipo"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="product">Producto para venta</option><option value="raw">Materia prima</option></select></Field><Field label="Nombre"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej. Termo 20 oz"/></Field><Field label="Categoría del cotizador"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="laser">Láser</option><option value="3d">Impresión 3D</option><option value="cricut">Cricut</option></select></Field><Field label="Proveedor"><input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></Field><Field label="Cantidad comprada"><input type="number" min="1" value={form.purchaseQty} onChange={e=>setForm({...form,purchaseQty:e.target.value})}/></Field><Field label="Costo total de compra"><input type="number" min="0" value={form.purchaseTotal} onChange={e=>setForm({...form,purchaseTotal:e.target.value})}/></Field><Field label="Existencia actual"><input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></Field><Field label="Existencia mínima"><input type="number" min="0" value={form.minStock} onChange={e=>setForm({...form,minStock:e.target.value})}/></Field><Field label="Precio de venta por pieza"><input type="number" min="0" value={form.salePrice} onChange={e=>setForm({...form,salePrice:e.target.value})}/></Field><Field label="Fecha de compra"><input type="date" value={form.purchaseDate} onChange={e=>setForm({...form,purchaseDate:e.target.value})}/></Field></div><div className="calculated"><span>Costo unitario <b>{money(unitCost(form))}</b></span><span>Ganancia por unidad <b>{money(num(form.salePrice)-unitCost(form))}</b></span></div><div className="actions"><button className="primary" onClick={save}><Save size={18}/>{editing?'Guardar cambios':'Agregar'}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(freshStock)}}>Cancelar</button>}</div></Card>
    <Card title="Existencias" subtitle={`${shown.length} artículos`}><SearchBox value={search} setValue={setSearch} placeholder="Buscar material, producto o proveedor…"/>{shown.length?<div className="inventoryGrid">{shown.map(i=><article className="inventoryCard" key={i.id}><div className="inventoryIcon">{i.type==='raw'?<Box/>:<Package/>}</div><div className="grow"><div className="itemTitle"><h3>{i.name}</h3>{num(i.stock)<=num(i.minStock)&&<span className="stockAlert">Stock bajo</span>}</div><p>{categoryName(i.category)} · {i.supplier||'Sin proveedor'}</p><div className="itemNumbers"><span>Existencia <b>{num(i.stock)}</b></span><span>Costo <b>{money(unitCost(i))}</b></span><span>Venta <b>{money(i.salePrice)}</b></span></div></div><div className="rowActions"><button onClick={()=>{setEditing(i.id);setForm({...freshStock,...i,category:['laser','3d','cricut'].includes(i.category)?i.category:'laser'});scrollTo({top:0,behavior:'smooth'})}}>Editar</button><button className="iconButton danger" onClick={()=>confirm('¿Eliminar este artículo?')&&setItems(items.filter(x=>x.id!==i.id))}><Trash2 size={16}/></button></div></article>)}</div>:<Empty text="Todavía no hay artículos registrados."/>}</Card></>
}

function Clients({clients,setClients}){
  const [form,setForm]=useState(freshClient),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),shown=clients.filter(c=>`${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(search.toLowerCase()))
  const save=()=>{if(!form.name.trim())return alert('Escribe el nombre.');const c={...form,id:editing||uid()};setClients(editing?clients.map(x=>x.id===editing?c:x):[c,...clients]);setForm(freshClient);setEditing(null)}
  return <><Card title={editing?'Editar cliente':'Nuevo cliente'} subtitle="Guarda sus datos para futuras cotizaciones."><div className="formGrid"><Field label="Nombre"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Teléfono / WhatsApp"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Correo"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Notas"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className="actions"><button className="primary" onClick={save}><Save size={18}/>Guardar cliente</button>{editing&&<button onClick={()=>{setEditing(null);setForm(freshClient)}}>Cancelar</button>}</div></Card>
    <Card title="Directorio" subtitle={`${shown.length} clientes`}><SearchBox value={search} setValue={setSearch} placeholder="Buscar cliente…"/>{shown.length?shown.map(c=><div className="listRow clientRow" key={c.id}><div className="avatar"><UserRound/></div><div className="grow"><b>{c.name}</b><span>{c.phone||c.email||'Sin contacto'}</span></div><button onClick={()=>{setEditing(c.id);setForm(c)}}>Editar</button><button className="iconButton danger" onClick={()=>confirm('¿Eliminar este cliente?')&&setClients(clients.filter(x=>x.id!==c.id))}><Trash2 size={16}/></button></div>):<Empty text="Aún no hay clientes."/>}</Card></>
}

function Quotes({quotes,setQuotes}){
  const [search,setSearch]=useState(''),shown=quotes.filter(q=>`${q.client} ${q.project} ${q.folio}`.toLowerCase().includes(search.toLowerCase()))
  return <Card title="Cotizaciones" subtitle={`${quotes.length} guardadas`}><SearchBox value={search} setValue={setSearch} placeholder="Buscar por cliente, proyecto o folio…"/>{shown.length?<div className="tableWrap"><table><thead><tr><th>Fecha</th><th>Servicio</th><th>Folio</th><th>Cliente</th><th>Proyecto</th><th>Total</th><th/></tr></thead><tbody>{shown.map(q=><tr key={q.id}><td>{new Date(q.date).toLocaleDateString('es-MX')}</td><td>{q.service||'Impresión 3D'}</td><td>{q.folio||'—'}</td><td>{q.client||'—'}</td><td>{q.project||'—'}</td><td><b>{money(q.total)}</b></td><td><button className="iconButton danger" onClick={()=>confirm('¿Eliminar esta cotización?')&&setQuotes(quotes.filter(x=>x.id!==q.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>:<Empty text="Todavía no hay cotizaciones."/>}</Card>
}

function Models({models,setModels,settings}){
  const [form,setForm]=useState({name:'',material:settings.materials[0]?.id||'pla',weight:0,hours:0,minutes:0})
  const save=()=>{if(!form.name.trim())return alert('Escribe el nombre.');setModels([{...form,id:uid()},...models]);setForm({...form,name:'',weight:0,hours:0,minutes:0})}
  return <><Card title="Nuevo modelo frecuente" subtitle="Guarda diseños para cotizar más rápido."><div className="formGrid"><Field label="Nombre"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Material"><select value={form.material} onChange={e=>setForm({...form,material:e.target.value})}>{settings.materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Peso (g)"><input type="number" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></Field><div className="splitFields"><Field label="Horas"><input type="number" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></Field><Field label="Minutos"><input type="number" value={form.minutes} onChange={e=>setForm({...form,minutes:e.target.value})}/></Field></div></div><div className="actions"><button className="primary" onClick={save}><Save size={18}/>Guardar modelo</button></div></Card>
    <Card title="Biblioteca de modelos" subtitle={`${models.length} modelos`}>{models.length?<div className="modelGrid">{models.map(m=><article key={m.id}><div className="modelIcon"><Box/></div><h3>{m.name}</h3><p>{settings.materials.find(x=>x.id===m.material)?.name||'Material'} · {m.weight} g</p><span>{m.hours} h {m.minutes} min</span><button className="iconButton danger" onClick={()=>confirm('¿Eliminar este modelo?')&&setModels(models.filter(x=>x.id!==m.id))}><Trash2 size={16}/></button></article>)}</div>:<Empty text="Aún no hay modelos guardados."/>}</Card></>
}

function SettingsPage({settings,setSettings}){
  const [draft,setDraft]=useState(settings);useEffect(()=>setDraft(settings),[settings])
  const mat=(id,k,v)=>setDraft({...draft,materials:draft.materials.map(m=>m.id===id?{...m,[k]:v}:m)})
  return <Card title="Configuración" subtitle="Ajusta los costos del cotizador."><div className="formGrid"><Field label="Nombre del negocio"><input value={draft.businessName||''} onChange={e=>setDraft({...draft,businessName:e.target.value})}/></Field><Field label="Teléfono / WhatsApp"><input value={draft.phone||''} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Field><Field label="Impresora"><input value={draft.printer} onChange={e=>setDraft({...draft,printer:e.target.value})}/></Field><Field label="Electricidad ($/kWh)"><input type="number" step=".01" value={draft.electricityPrice} onChange={e=>setDraft({...draft,electricityPrice:e.target.value})}/></Field><Field label="Consumo (W)"><input type="number" value={draft.printerWatts} onChange={e=>setDraft({...draft,printerWatts:e.target.value})}/></Field><Field label="Desgaste 3D por hora"><input type="number" value={draft.wearPerHour} onChange={e=>setDraft({...draft,wearPerHour:e.target.value})}/></Field><Field label="Láser: costo por hora"><input type="number" value={draft.laserRate??defaults.laserRate} onChange={e=>setDraft({...draft,laserRate:e.target.value})}/></Field><Field label="Cricut: costo por hora"><input type="number" value={draft.cricutRate??defaults.cricutRate} onChange={e=>setDraft({...draft,cricutRate:e.target.value})}/></Field><Field label="Ganancia predeterminada (%)"><input type="number" value={draft.defaultProfit} onChange={e=>setDraft({...draft,defaultProfit:e.target.value})}/></Field><Field label="Redondear a ($)"><input type="number" value={draft.roundTo} onChange={e=>setDraft({...draft,roundTo:e.target.value})}/></Field><Field label="Vigencia (días)"><input type="number" value={draft.quoteValidity||15} onChange={e=>setDraft({...draft,quoteValidity:e.target.value})}/></Field></div>
    <div className="sectionHeader"><div><h3>Materiales de impresión 3D</h3><p>Precio por kilogramo</p></div><button onClick={()=>setDraft({...draft,materials:[...draft.materials,{id:uid(),name:'Nuevo material',priceKg:0}]})}><Plus size={17}/>Agregar</button></div><div className="materials">{draft.materials.map(m=><div className="materialRow" key={m.id}><input value={m.name} onChange={e=>mat(m.id,'name',e.target.value)}/><input type="number" value={m.priceKg} onChange={e=>mat(m.id,'priceKg',e.target.value)}/><button className="iconButton danger" onClick={()=>setDraft({...draft,materials:draft.materials.filter(x=>x.id!==m.id)})}><Trash2 size={17}/></button></div>)}</div>
    <SheetCatalog title="Materiales de láser" allowUnit list={draft.laserMaterials||defaults.laserMaterials} onChange={list=>setDraft({...draft,laserMaterials:list})}/>
    <SheetCatalog title="Materiales de Cricut" allowMeter list={draft.cricutMaterials||defaults.cricutMaterials} onChange={list=>setDraft({...draft,cricutMaterials:list})}/>
    <div className="actions"><button className="primary" onClick={()=>{setSettings(draft);alert('Configuración guardada.')}}><Save size={18}/>Guardar configuración</button><button onClick={()=>setDraft(defaults)}><RotateCcw size={18}/>Restaurar</button></div><div className="syncNotice"><Archive/><div><b>Sincronización entre dispositivos</b><p>Actualmente se guarda en este dispositivo. La estructura está lista para conectar una base de datos posteriormente.</p></div></div></Card>
}

function SheetCatalog({title,list,onChange,allowMeter=false,allowUnit=false}){
  const update=(id,key,value)=>onChange(list.map(m=>m.id===id?{...m,[key]:value}:m))
  return <><div className="sectionHeader"><div><h3>{title}</h3><p>{allowMeter?'Selecciona si compras por metro de rollo o por hoja':allowUnit?'Compra por placa, hoja o por pieza':'Tamaño de placa u hoja en centímetros'}</p></div><button onClick={()=>onChange([...list,{id:uid(),name:'Nuevo material',pricingMode:allowMeter?'meter':'sheet',sheetWidth:30,sheetHeight:allowMeter?100:30,sheetCost:0,waste:0}])}><Plus size={17}/>Agregar</button></div>
    <div className="sheetMaterials">{list.map(m=><div className="sheetRow" key={m.id}>
      <label className="sheetField"><span>Material</span><input value={m.name} onChange={e=>update(m.id,'name',e.target.value)} placeholder="Material"/></label>
      {(allowMeter||allowUnit)&&<label className="sheetField"><span>Forma de compra</span><select value={m.pricingMode||'sheet'} onChange={e=>{const mode=e.target.value;onChange(list.map(x=>x.id===m.id?{...x,pricingMode:mode,sheetHeight:mode==='meter'?100:x.sheetHeight}:x))}}>{allowMeter&&<option value="meter">Rollo por metro</option>}<option value="sheet">Por hoja / placa</option>{allowUnit&&<option value="unit">Por pieza</option>}</select></label>}
      <label className="sheetField"><span>{m.pricingMode==='meter'?'Ancho del rollo (cm)':m.pricingMode==='unit'?'Ancho del producto (cm)':'Ancho de hoja / placa (cm)'}</span><input type="number" step=".1" value={m.sheetWidth} onChange={e=>update(m.id,'sheetWidth',e.target.value)} placeholder="Ancho"/></label>
      <label className="sheetField"><span>{m.pricingMode==='meter'?'Largo base (100 cm)':m.pricingMode==='unit'?'Alto del producto (cm)':'Largo de hoja / placa (cm)'}</span><input type="number" step=".1" disabled={m.pricingMode==='meter'} value={m.pricingMode==='meter'?100:m.sheetHeight} onChange={e=>update(m.id,'sheetHeight',e.target.value)} placeholder="Largo"/></label>
      <label className="sheetField"><span>{m.pricingMode==='meter'?'Costo por metro ($)':m.pricingMode==='unit'?'Costo de compra por pieza ($)':'Costo por hoja / placa ($)'}</span><input type="number" step=".01" value={m.sheetCost} onChange={e=>update(m.id,'sheetCost',e.target.value)} placeholder="Costo"/></label>
      {m.pricingMode!=='unit'&&<label className="sheetField"><span>Merma (%)</span><input type="number" step="1" value={m.waste} onChange={e=>update(m.id,'waste',e.target.value)} placeholder="%"/></label>}
      <button className="iconButton danger" aria-label={`Eliminar ${m.name}`} onClick={()=>onChange(list.filter(x=>x.id!==m.id))}><Trash2 size={17}/></button>
    </div>)}</div></>
}

function Card({title,subtitle,children}){return <section className="card"><div className="cardTitle"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>}
function Field({label,children,full}){return <label className={`field ${full?'full':''}`}><span>{label}</span>{children}</label>}
function Line({label,value,bold}){return <div className={`line ${bold?'bold':''}`}><span>{label}</span><b>{money(value)}</b></div>}
function Stat({label,value,tone}){return <article className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong></article>}
function Empty({text}){return <div className="empty"><Archive/><p>{text}</p></div>}
function SearchBox({value,setValue,placeholder}){return <label className="searchBox"><Search size={18}/><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/></label>}
createRoot(document.getElementById('root')).render(<App/>)
